language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - NUMPY_VERSION=1.7.1 ONLY_EGG_INFO=false
  - NUMPY_VERSION=1.6.2 ONLY_EGG_INFO=false
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install -qq python-numpy python-scipy python-matplotlib
install:
 - export PYTHONIOENCODING=UTF8
 - pip install --upgrade "numpy==$NUMPY_VERSION" -q --use-mirrors
 - pip install matplotlib --use-mirrors
 - pip install scipy --use-mirrors
 - pip install pyfits --use-mirrors
script: nosetests
notifications:
  email: false
